openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MVALENZDELVI/api-customer/1.0.0
info:
  title: Customer Microservice
  description: Customer Microservice
  version: 1.0.0
paths:
  /customer:
    post:
      tags:
        - customer
      summary: Add a new customer to the database
      description: Add a new customer to the database
      operationId: save
      requestBody:
        description: Create a new customer in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        "405":
          description: Invalid input
  /customer/{id}:
    put:
      tags:
        - customer
      summary: Update an existing customer
      description: Update an existing customer by Id
      operationId: update
      parameters:
        - name: id
          in: path
          description: ID of customer to update
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent customer in the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid ID supplied
        "404":
          description: Customer not found
        "405":
          description: Validation exception
    get:
      tags:
        - customer
      summary: Find customer by ID
      description: Returns a single customer
      operationId: findById
      parameters:
        - name: id
          in: path
          description: ID of customer to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid ID supplied
        "404":
          description: Customer not found
    delete:
      tags:
        - customer
      summary: Delete a customer
      description: delete a customer
      operationId: delete
      parameters:
        - name: id
          in: path
          description: Customer id to delete
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "400":
          description: Invalid customer value
  /customer/document/{document}:
    get:
      tags:
        - customer
      summary: Find customer by document
      description: Returns a single customer
      operationId: findByDocument
      parameters:
        - name: document
          in: path
          description: document of customer to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid document supplied
        "404":
          description: Customer not found
  /customer/phone/{phone}:
    get:
      tags:
        - customer
      summary: Find customer by phone
      description: Returns a single customer
      operationId: findByPhone
      parameters:
        - name: phone
          in: path
          description: phone of customer to return
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid phone supplied
        "404":
          description: Customer not found
components:
  schemas:
    Personal:
      required:
        - names
        - fatherLastName
        - motherLastName
        - documentType
        - documentNumber
        - profile
      type: object
      properties:
        names:
          type: string
          description: Names
          pattern: '^(?=.{3,15}$)[A-ZÁÉÍÓÚ][a-zñáéíóú]+(?: [A-ZÁÉÍÓÚ][a-zñáéíóú]+)?$'
          x-pattern-message: "invalid Names"
          example: Max Henry
        fatherLastName:
          type: string
          description: Father last name
          pattern: '^(?=.{3,15}$)[A-ZÁÉÍÓÚ][a-zñáéíóú]+(?: [A-ZÁÉÍÓÚ][a-zñáéíóú]+)?$'
          x-pattern-message: "invalid fatherLastName"
          example: Valenzuela
        motherLastName:
          type: string
          description: Mother last name
          pattern: '^(?=.{3,15}$)[A-ZÁÉÍÓÚ][a-zñáéíóú]+(?: [A-ZÁÉÍÓÚ][a-zñáéíóú]+)?$'
          x-pattern-message: "invalid motherLastName"
          example: Del Villar
        documentType:
          type: string
          description: Document type
          enum:
            - DNI
            - CEX
            - Pasaporte
        documentNumber:
          type: string
          description: Document number
          minimum: 8
          maximum: 9
          pattern: '[0-9]{8,9}'
          x-pattern-message: "invalid document number"
          example: "40605547"
        profile:
          type: string
          description: Profile
          enum:
            - Normal
            - VIP
    Business:
      required:
        - legalName
        - fullName
        - profile
      type: object
      properties:
        legalName:
          type: string
          description: Name
          example: MAXWARE SAC
        fullName:
          type: string
          description: Name
          example: MAXWARE SYSTEM SAC
        ruc:
          type: string
          description: RUC
          minimum: 11
          maximum: 11
          pattern: '[0-9]{11}'
          x-pattern-message: "invalid ruc"
          example: "20304050603"
        profile:
          type: string
          description: Profile
          enum:
            - Normal
            - PYME
    Customer:
      required:
        - type
        - email
        - phone
      type: object
      properties:
        id:
          type: string
          readOnly: true
        type:
          type: string
          description: Customer type
          enum:
            - personal
            - business
        personal:
          $ref: '#/components/schemas/Personal'
        business:
          $ref: '#/components/schemas/Business'
        email:
          type: string
          description: Email
          pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$'
          x-pattern-message: "invalid Email"
          example: mvalenzdelvi@gmail.com
        phone:
          type: string
          description: Phone
          pattern: '(\+51|51|)[0-9]+'
          x-pattern-message: "invalid Phone"
          example: "+51962917953"
        imei:
          type: string
          description: IMEI
          x-pattern-message: "invalid IMEI"
          example: "29-123456-654321-3"
        createdAt:
          type: string
          format: date-time
          description: Creation date
          example: "2023-12-01T20:30:00Z"
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Updated date
          example: "2023-12-01T20:30:00Z"
          readOnly: true
  requestBodies:
    customer:
      description: customer object that needs to be added to the database
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Customer'